-- 벌교미래엔영어 학원관리대시보드
-- 숙제 제출 전용 Supabase 테이블

create table if not exists public.homework_submissions (
  id bigint generated by default as identity primary key,
  student_id text null,
  student_name text not null,
  phone text null,
  homework_title text null,
  homework_content text null,
  submission_status text not null default 'submitted',
  attachment_url text null,
  submitted_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists homework_submissions_submitted_at_idx
  on public.homework_submissions (submitted_at desc);

create index if not exists homework_submissions_student_name_idx
  on public.homework_submissions (student_name);

create or replace function public.set_homework_submissions_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_homework_submissions_updated_at
  on public.homework_submissions;

create trigger set_homework_submissions_updated_at
before update on public.homework_submissions
for each row
execute function public.set_homework_submissions_updated_at();

alter table public.homework_submissions enable row level security;

drop policy if exists "homework anonymous insert only" on public.homework_submissions;
create policy "homework anonymous insert only"
on public.homework_submissions
for insert
to anon, authenticated
with check (
  student_name is not null
  and length(trim(student_name)) > 0
);

-- 보안 원칙:
-- anon/authenticated에는 SELECT/UPDATE/DELETE 정책을 만들지 않습니다.
-- 전체 목록 조회, 수정, 삭제는 Vercel 서버 API에서 SUPABASE_SERVICE_ROLE_KEY로만 처리합니다.
-- Supabase service_role은 RLS를 우회하므로 브라우저 코드에 절대 노출하면 안 됩니다.

grant insert on public.homework_submissions to anon, authenticated;
grant usage, select on sequence public.homework_submissions_id_seq to anon, authenticated;

-- Realtime 사용을 위해 publication에 테이블을 추가합니다.
-- 이미 추가되어 있다는 오류가 나면 무시해도 됩니다.
do $$
begin
  alter publication supabase_realtime add table public.homework_submissions;
exception
  when duplicate_object then null;
end;
$$;
